### ISSUE TITLE
Add all tokenattribute types

### ISSUE THREAD

**Issue by dainiusjocas** [quarkiverse/quarkus-lucene#6]
In this [PR]() I've added a couple of attribute types that covered support for some use cases.

Is there a reason why not all attributes from package `org.apache.lucene.analysis.tokenattributes` are added? Maybe we can just add them all?

**Comment by gustavonalle** [comment]
I am looking at it now, before releasing 0.2

**Comment by gustavonalle** [comment]
Fixed by #7
